bundler_args: ""
script: "bundle exec rake test"
gemfile:
 - gemfiles/shoulda2.gemfile
 - gemfiles/shoulda3.gemfile
rvm:
  - ree
  - 1.9.3
  - 2.0.0
  - 2.1.0
matrix:
  exclude:
    - rvm: ree
      gemfile: gemfiles/shoulda3.gemfile
